# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Egemen Mede (DeliPenguen)"

author:
  facebook:         emede
  youtubeChannel:   UC4ZfN6F8_zJQK_oMe3xaUcA
  twitter:          delipenguen
  github:           egemenmede
  stackoverflow:    504641
  linkedin:         egemenmede
  googlePlus:       +EgemenMEDE
  medium:           delipenguen
  email:            egemenmede@gmail.com

copyright:
  year:             2017
  name:             Egemen Mede

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "delipenguen"
# id:               "kiko-plus"

# URL
url:                "https://egemenmede.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Turkey
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           10
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "Köşe Yazıları"
    url:            "/articles"
  - name:           "Projeler"
    url:            "/projects"
  - name:           "Seminerler"
    url:            "/seminars"
  - name:           "Kitap"
    url:            "/book"
  - name:           "Hakkında"
    url:            "/about"
  - name:           "Etiketler"
    url:            "/tags"
  - name:           "Arşiv"
    url:            "/archive"
  - name:           "Github"
    url:            "https://github.com/egemenmede/egemenmede.github.io"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]
